<main class="container py-5">
    <form>
        <fieldset class="my-1">
            <label for="email" class="form-label">
                <?= $this->translator->translate("login_email_label") ?>
            </label>
            <input type="email" name="email" id="email" class="form-control"/>
        </fieldset>
        <fieldset class="my-1">
            <label for="password" class="form-label">
                <?= $this->translator->translate("login_password_label") ?>
            </label>
            <input type="password" name="password" id="password" class="form-control"/>
        </fieldset>
        <fieldset class="my-4">
            <button type="submit" class="btn btn-primary"><?= $this->translator->translate("login_submit_button") ?></button>
        </fieldset>
    </form>
    <p>
        <?= $this->translator->translate("login_register_text") ?> <a href="index.php?route=register"> <?= $this->translator->translate("login_link_text") ?> </a>
    </p>
</main>